config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/portfolio'
  get 'home/about'
  get 'home/contact'
  get 'home/resume'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def portfolio
  end

  def about
  end

  def contact
  end

  def resume
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_about.html.erb
<section id="home-about">

    <div class="scroll-1">
      <%# <h1 class="home other">Home <span class="small">01</span></h1> %>
      <h1 class="projects other">Projects <span class="small">02</span></h1>
      <h1 class="big abouts">About <span class="small">03</span></h1> 
      <h1 class="contact other">Contact <span class="small">03</span></h1>
      <%# <hr> %>
    </div>

    <div class="container">
        <div class="dev-tools">             
            <div class="html">
                <i class="fab fa-html5 fa-3x"></i>
                <h5>HTML</h5>
                <p></p>
            </div>
            <div class="css">
                <i class="fab fa-css3 fa-3x"></i>
                <h5>CSS</h5>
                <p></p>
            </div>
            <div class="Sass">
                <i class="fab fa-sass fa-3x"></i>
                <h5>SASS</h5>
                <p></p>
            </div>
            <div class="javascript">
                <i class="fab fa-js fa-3x"></i>
                <h5>Javascript</h5>
                <p></p>
            </div>
            <div class="ruby">
                <i class="fas fa-gem fa-3x"></i>
                <h5>Ruby on rails</h5>
                <p></p>
            </div>       
        </div>


        <div class="about-me">
            <div class="img-wrapper">
                <h2 class="say-hi">Say hi.</h2>

                <div clas="left-img">
                    <div class="object"></div>
                    <div class="img"></div>
                </div>
            </div>

            <div class="text">
                <h3>Chinonso John Nkpolukwu</h3>
                <!-- <hr> -->
                <br>
                <p>I’m a Melbourne based software developer student and professional, with a passion for code and everything technology. I love creating things and share an equal passion for playing sports and keeping fit.</p>
                <br>
                <button><%= link_to "Read More", asset_path("resume.pdf") %></button>
            </div>
        </div>






    </div>
    

</section>

app/views/home/_contact.html.erb
<section id="home-contact">

    <div class="scroll-1">
      <%# <h1 class="home other">Home <span class="small">01</span></h1> %>
      <%# <h1 class="projects other">Projects <span class="small">02</span></h1> %>
      <h1 class="abouts other">About <span class="small">03</span></h1> 
      <h1 class="big contact">Contact <span class="small">04</span></h1>
      <h1 class="footer other">Footer <span class="small">05</span></h1>
      <%# <hr> %>
    </div>

    <div class="container">
        <div class="map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d8445.803562404395!2d144.94685213752544!3d-37.814041970651736!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6ad65d4ee2d152c5%3A0x38a0908dae999c56!2s220%20Spencer%20St%2C%20Melbourne%20VIC%203000!5e0!3m2!1sen!2sau!4v1605359304336!5m2!1sen!2sau" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
        </div>

        <div class="form-div">

            <h3>Have a question or want to work together?</h3>
            <form action="https://formspree.io/f/xdopveao" method="POST" id="my-form">
                <div class="form-group">
                    <label for="name"></label>
                    <input type="text" id="name" name="name" placeholder="Name">
                </div>

                <div class="form-group">
                    <label for="email"></label>
                    <input type="email" id="email" name="email" placeholder="Email">
                </div>

                <div class="form-group">
                    <label for="message"></label>
                    <textarea name="message" id="message" cols="30" rows="10" placeholder="Your Message"></textarea>
                </div>

                <button type="submit">Submit</button>
            <form>

        </div>
        <%# <div id="status">Message Sent!</div> %>
    
    </div>
    <script src="packs/application.js"></script>

</section>

app/views/home/_footer.html.erb
<section class="test" id="home-footer">
    <footer id="main-footer">
        <button>
            <i class="arrow fas fa-angle-up fa-3x"></i>
        </button>
        <div class="footer-container">
            <div class="linkedin">
                <a href="https://www.linkedin.com/in/chinonso-john-nkpolukwu-521201138/"><i class="fab fa-linkedin-in fa-2x"></i></a>
            </div>
            <div class="instagram">
                <a href="https://www.instagram.com/johnnsonkp/"><i class="fab fa-instagram fa-2x"></i></a>
            </div>
            <div class="codepen">
                <a href="https://codepen.io/Johnnsonkp"><i class="fab fa-codepen fa-2x"></i></a>
            </div>
            <div class="github">
                <a href="https://github.com/Johnnsonkp"><i class="fab fa-github fa-2x"></i></a>
            </div>
        </div>
        <h5><span class="highlight">Johnnsonkp</span> &copy2021 </h5>
    </footer>
</section>

app/views/home/_header.html.erb
<section id="home-header">
    <div class="container">
       <div class="right">
        <%= link_to "Johnnsonkp", root_path, class:"hero-text" %>
       </div>


        <!--hamburger menu -->
        <div id="hamburger-menu">
            <nav class="right">
                
                <div class="circle" id="open">
                    <%# <button id="close">
                        <i class="fas fa-times"></i>
                    </button> %>
                    <button id="open">
                        <i class="fas fa-bars"></i>
                    </button>
                </div>


                <%# <label for="toggle"></label>
                <input type="checkbox" id="menuShowHide" id="toggle">
                <label for="menuShowHide"></label> %>
                    <ul id="mainMenu">
                        <li><%= link_to "Home", root_path, class:"menu-li home-li"%></li>
                        <li><%= link_to "Portfolio", home_portfolio_path, class:"menu-li portfolio"%></li>
                        <li><%= link_to "About", home_about_path, class:"menu-li about"%></li>
                        <li><%= link_to "Contact", home_contact_path, class:"menu-li contact"%></li>
                        <%= link_to 'Resume', asset_path("resume.pdf"), { :class=>"resume-button" } %>
                        
                    </ul> 
            </nav>
        </div>
    </div>
</section>

app/views/home/_projects.html.erb
<section id="home-projects">

    <div class="scroll-1">
      <h1 class="home other">Home <span class="small">01</span></h1>
      <h1 class="big projects">Projects <span class="small">02</span></h1>
      <h1 class="abouts other">About <span class="small">03</span></h1> 
      <%# <hr> %>
    </div>

    <div class="btn-div">
        <button class="day-night">O</button>
    </div>
    
    

    <div class="container">
    
        <div class="main">
            
            <div class="project">
                <a href="https://itemsv3.herokuapp.com/">
                    <div class="img img-one">
                            <div class="project-info">
                                <%# <h4>Items V3</h4> %>
                                <span>
                                <h4>ITEMS v3 </h4>
                                <br>
                                <strong>TECH STACK:</strong> HTML, CSS, SCSS, Javascript, Ruby on Rails</span>
                                
                            </div>
                            <div class="overview">
                                <h3>Overview</h3>
                                <br>
                                <p>A wishlist shopping cart application designed to organise, prioritize, and store all your
                                    online shopping items.. 
                                </p>
                            </div>
                    </div>
                </a>
            </div>
            

        <div class="project">
            <a href="https://github.com/Johnnsonkp/movie-app">
                <div class="img img-two">
                    <div class="project-info">
                        <%# <h3>Project Two</h3> %>
                        <span>
                            <h4>MOVIE DB</h4>
                            <br>
                            <strong>TECH STACK:</strong> HTML, CSS, SCSS, Javascript, Ruby on Rails</span>
                    </div>
                    <div class="overview">
                        <h3>Overview</h3>
                        <br>
                        <p>A Movie DB application created using fetch API. </p>
                    </div>
                </div>
            </a>
        </div>

            <div class="project">
                <a href="https://johnnsonkp-portfolio.netlify.app/">
                    <div class="img img-three">
                        <div class="project-info">
                            <%# <h3>Porfolio V1</h3> %>
                            <span>
                            <h4>PORTFOLIO v1</h4>
                            <br>
                            <strong>TECH STACK:</strong> HTML, CSS, SCSS, Javascript, Ruby on Rails</span>
                        </div>
                        <div class="overview">
                            <h3>Overview</h3>
                            <br>
                            <p>Version one of my porfolio. </p>
                        </div>
                    </div>
                </a>
           </div> 

           <div class="project">
                <a href="https://github.com/Johnnsonkp/nba-stats">
                    <div class="img img-four">
                        <div class="project-info">
                            <%# <h3>Porfolio V1</h3> %>
                            <span>
                            <h4>NBA STATS</h4>
                            <br>
                            <strong>TECH STACK:</strong> HTML, CSS, SCSS, Javascript, Ruby on Rails</span>
                        </div>
                        <div class="overview">
                            <h3>Overview</h3>
                            <br>
                            <p>NBA stats app showcasing different NBA players and team stats (still in development) </p>
                        </div>
                    </div>
                </a>
           </div> 

           <div class="project">
                <a href="https://codepen.io/Johnnsonkp/pen/oNzbGpX">
                    <div class="img img-five">
                        <div class="project-info">
                            <%# <h3>Porfolio V1</h3> %>
                            <span>
                            <h4>TRAVEL BUCKETLIST</h4>
                            <br>
                            <strong>TECH STACK:</strong> HTML, CSS, SCSS, Javascript, Ruby on Rails</span>
                        </div>
                        <div class="overview">
                            <h3>Overview</h3>
                            <br>
                            <p>Simple expanding cards application</p>
                        </div>
                    </div>
                </a>
           </div>

           <div class="project">
                <a href="https://codepen.io/Johnnsonkp/pen/ExyQpro">
                    <div class="img img-six">
                        <div class="project-info">
                            <%# <h3>Porfolio V1</h3> %>
                            <span>
                            <h4>ASAP-MOB</h4>
                            <br>
                            <strong>TECH STACK:</strong> HTML, CSS, SCSS, Javascript, Ruby on Rails</span>
                        </div>
                        <div class="overview">
                            <h3>Fan Tribute Page</h3>
                            <br>
                            <p>Simple html and CSS fan tribute page designed for a challenge in my studies.</p>
                        </div>
                    </div>
                </a>
           </div>


        </div>
    
    </div>


</section>

app/views/home/about.html.erb
<section id="home-about">

    <div class="scroll-1">
      <%# <h1 class="home other">Home <span class="small">01</span></h1> %>
      <h1 class="projects other">Projects <span class="small">02</span></h1>
      <h1 class="big abouts">About <span class="small">03</span></h1> 
      <h1 class="contact other">Contact <span class="small">03</span></h1>
      <%# <hr> %>
    </div>

    <div class="container">
        <div class="dev-tools">             
            <div class="html">
                <i class="fab fa-html5 fa-3x"></i>
                <h5>HTML</h5>
                <p></p>
            </div>
            <div class="css">
                <i class="fab fa-css3 fa-3x"></i>
                <h5>CSS</h5>
                <p></p>
            </div>
            <div class="Sass">
                <i class="fab fa-css3 fa-3x"></i>
                <h5>SASS</h5>
                <p></p>
            </div>
            <div class="javascript">
                <i class="fab fa-js fa-3x"></i>
                <h5>Javascript</h5>
                <p></p>
            </div>
            <div class="ruby">
                <i class="fas fa-gem fa-3x"></i>
                <h5>Ruby on rails</h5>
                <p></p>
            </div>       
        </div>


        <div class="about-me">
            <div class="img-wrapper">
                <h2 class="say-hi">Say hi.</h2>

                <div clas="left-img">
                    <div class="object"></div>
                    <div class="img"></div>
                </div>
            </div>

            <div class="text">
                <h3>Chinonso John Nkpolukwu</h3>
                <!-- <hr> -->
                <br>
                <p>I’m a Melbourne based software developer student and professional, with a passion for code and everything technology. I love creating things and share an equal passion for playing sports and keeping fit.</p>
                <br>
                <button><%= link_to "Read More", asset_path("resume.pdf") %></button>
            </div>
        </div>

    </div>
    

</section>

app/views/home/contact.html.erb
<section id="home-contact">

    <div class="scroll-1">
      <%# <h1 class="home other">Home <span class="small">01</span></h1> %>
      <%# <h1 class="projects other">Projects <span class="small">02</span></h1> %>
      <h1 class="abouts other">About <span class="small">03</span></h1> 
      <h1 class="big contact">Contact <span class="small">04</span></h1>
      <h1 class="footer other">Footer <span class="small">05</span></h1>
      <%# <hr> %>
    </div>

    <div class="container">
        <div class="map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d8445.803562404395!2d144.94685213752544!3d-37.814041970651736!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6ad65d4ee2d152c5%3A0x38a0908dae999c56!2s220%20Spencer%20St%2C%20Melbourne%20VIC%203000!5e0!3m2!1sen!2sau!4v1605359304336!5m2!1sen!2sau" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
        </div>

        <div class="form-div">

            <h3>Have a question or want to work together?</h3>
            <form action="https://formspree.io/f/xdopveao" method="POST" id="my-form">
                <div class="form-group">
                    <label for="name"></label>
                    <input type="text" id="name" name="name" placeholder="Name">
                </div>

                <div class="form-group">
                    <label for="email"></label>
                    <input type="email" id="email" name="email" placeholder="Email">
                </div>

                <div class="form-group">
                    <label for="message"></label>
                    <textarea name="message" id="message" cols="30" rows="10" placeholder="Your Message"></textarea>
                </div>

                <button type="submit">Submit</button>
            <form>

        </div>
        <%# <div id="status">Message Sent!</div> %>
    
    </div>
</section>

app/views/home/index.html.erb
<section id="home-index">

    <%# <div class="scroll-1">
      <h1 class="big home">Home <span class="small">01</span></h1>
      <h1 class="projects">Projects <span class="small">02</span></h1>
      <h1 class="abouts">About <span class="small">03</span></h1> 
    </div> %>

    <div class="video-container">
        <video src="assets/tech.mp4" type="video/mp4" autoplay muted  loop playsinline>
        </video>
    </div>

    <!-- View my work button -->
    
    <div class="middle-text">
        <%= link_to "", home_about_path, class:"img"%>
        <div class="inner-text">
            <h1>Hello, I’m <span class="primary-color">Chinonso John Nkpolukwu</span>.<br> I’m a full-stack web developer.</h1>
            <br>
            <br>
            <span class="btn project-btn">
                <span>View my work</span>
                <span class="fas fa-arrow-right"></span>
            </span>
        </div>
    </div>

    

    <%# <div class="scroll-1">
        <h1>HOME <span class="small">01</span></h1>
    </div> %>

</section>

<%= render 'home/projects' %>
<%= render 'home/about' %>
<%= render 'home/contact' %>

app/views/home/portfolio.html.erb
<section id="portfolio-link">
<section id="home-projects" id="projects-link">

    <div class="scroll-1">
      <h1 class="home other">Home <span class="small">01</span></h1>
      <h1 class="big projects">Projects <span class="small">02</span></h1>
      <h1 class="abouts other">About <span class="small">03</span></h1> 
      <%# <hr> %>
    </div>

    <div class="btn-div">
        <button class="day-night">O</button>
    </div>
    
    

    <div class="container">
    
        <div class="main">
            
            <div class="project">
                <div class="img img-one">
                    <div class="project-info">
                        <%# <h4>Items V3</h4> %>
                        <span>
                        <h4>ITEMS v3</h4>
                        <br>
                        <strong>TECH STACK:</strong> HTML, CSS, SCSS, Javascript, Ruby on Rails</span>
                    </div>
                    <div class="overview">
                        <h3>Overview</h3>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. </p>
                    </div>
                </div>
            
            </div>
            

        <div class="project">
            <div class="img img-two">
                <div class="project-info">
                    <%# <h3>Project Two</h3> %>
                    <span>
                        <h4>MOVIE DB</h4>
                        <br>
                        <strong>TECH STACK:</strong> HTML, CSS, SCSS, Javascript, Ruby on Rails</span>
                </div>
                <div class="overview">
                    <h3>Overview</h3>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. </p>
                </div>
            </div>
        </div>

            <div class="project">
                <div class="img img-three">
                    <div class="project-info">
                        <%# <h3>Porfolio V1</h3> %>
                        <span>
                        <h4>PORTFOLIO v1</h4>
                        <br>
                        <strong>TECH STACK:</strong> HTML, CSS, SCSS, Javascript, Ruby on Rails</span>
                    </div>
                    <div class="overview">
                        <h3>Overview</h3>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. </p>
                    </div>
                </div>
           </div> 

           <div class="project">
                <div class="img img-four">
                    <div class="project-info">
                        <%# <h3>Porfolio V1</h3> %>
                        <span>
                        <h4>NBA STATS</h4>
                        <br>
                        <strong>TECH STACK:</strong> HTML, CSS, SCSS, Javascript, Ruby on Rails</span>
                    </div>
                    <div class="overview">
                        <h3>Overview</h3>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. </p>
                    </div>
                </div>
           </div> 

           <div class="project">
                <div class="img img-five">
                    <div class="project-info">
                        <%# <h3>Porfolio V1</h3> %>
                        <span>
                        <h4>PORTFOLIO v1</h4>
                        <br>
                        <strong>TECH STACK:</strong> HTML, CSS, SCSS, Javascript, Ruby on Rails</span>
                    </div>
                    <div class="overview">
                        <h3>Overview</h3>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. </p>
                    </div>
                </div>
           </div>

           <div class="project">
                <div class="img img-six">
                    <div class="project-info">
                        <%# <h3>Porfolio V1</h3> %>
                        <span>
                        <h4>ASAP-MOB</h4>
                        <br>
                        <strong>TECH STACK:</strong> HTML, CSS, SCSS, Javascript, Ruby on Rails</span>
                    </div>
                    <div class="overview">
                        <h3>Overview</h3>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. </p>
                    </div>
                </div>
           </div>


        </div>
    
    </div>


</section>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortfolioV2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%# font awesome cdn %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />

    <%# Google fonts %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet"> 


  </head>

  <body>
    <%= render 'home/header' %>
    <%= yield %>
    <%= render 'home/footer' %>

  </body>
</html>